BEGIN;

ALTER TABLE ajax_players
ADD COLUMN IF NOT EXISTS arrival_deal JSONB;

UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"FC Barcelona","transferType":"Huur","fee":"Niet openbaar gemaakt","terms":["Gehuurd voor het seizoen 2026/27."],"note":"Ajax en FC Barcelona hebben geen huursom, koopoptie of salarisverdeling openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-huurt-marc-ter-stegen-van-fc-barcelona/"}]}'::jsonb WHERE id = 'ter-stegen';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Real Valladolid","transferType":"Definitieve transfer","fee":"Niet openbaar gemaakt","terms":[],"note":"Ajax heeft geen transfersom of aanvullende financiële afspraken openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-contracteert-lucas-rosa"}]}'::jsonb WHERE id = 'rosa';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Viborg FF","transferType":"Definitieve transfer","fee":"Niet openbaar gemaakt","terms":[],"note":"Ajax heeft geen transfersom of aanvullende financiële afspraken openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/artikelen/ajax-contracteert-anton-gaaei/"}]}'::jsonb WHERE id = 'gaaei';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Fenerbahçe","transferType":"Transfervrij","fee":"Geen transfersom","terms":["Amrabat beëindigde zijn contract bij Fenerbahçe voordat hij bij Ajax tekende."],"note":"Eventuele tekenpremies of andere persoonlijke afspraken zijn niet openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-contracteert-sofyan-amrabat"}]}'::jsonb WHERE id = 'amrabat';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"AZ","transferType":"Definitieve transfer","fee":"€10 miljoen","terms":["Ajax maakte een vaste transfersom van €10 miljoen bekend."],"note":"Eventuele aanvullende afspraken zijn niet openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/artikelen/ajax-en-az-bereiken-akkoord-over-owen-wijndal/"}]}'::jsonb WHERE id = 'wijndal';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"AS Monaco","transferType":"Huur","fee":"Niet openbaar gemaakt","terms":["Gehuurd voor de rest van het seizoen 2026/27."],"note":"Ajax en AS Monaco hebben geen huursom, salarisverdeling of koopoptie openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-en-as-monaco-bereiken-akkoord-over-thilo-kehrer/"}]}'::jsonb WHERE id = 'kehrer';
UPDATE ajax_players SET arrival_deal = '{"status":"partly_reported","updatedAt":"2026-09-08","fromClub":"Sunderland AFC","transferType":"Huur met koopoptie","fee":"Gemeld: circa €3,6–3,8 miljoen voor de tijdelijke deal","terms":["Ajax bevestigt een optie tot koop.","De koopoptie wordt in de berichtgeving op circa €16 miljoen geschat."],"note":"Ajax en Sunderland bevestigen de financiële bedragen niet; berichtgeving over de tijdelijke kosten verschilt licht.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/simon-adingra-op-huurbasis-naar-ajax/"},{"label":"Ajax1","url":"https://www.ajax1.nl/ajax-betaalt-miljoenenbedrag-voor-opvolger-godts-deal-dichtbij/"}]}'::jsonb WHERE id = 'adingra';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Borussia Dortmund","transferType":"Transfervrij","fee":"Geen transfersom","terms":[],"note":"Eventuele tekenpremies of andere persoonlijke afspraken zijn niet openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-contracteert-julian-brandt/"}]}'::jsonb WHERE id = 'brandt';
UPDATE ajax_players SET arrival_deal = '{"status":"partly_reported","updatedAt":"2026-09-08","fromClub":"RSC Anderlecht","transferType":"Definitieve transfer","fee":"Gemeld: €10 miljoen plus maximaal €2 miljoen","terms":["Een vaste som van circa €10 miljoen en maximaal €2 miljoen aan bonussen worden gemeld."],"note":"Ajax en RSC Anderlecht hebben het transferbedrag niet officieel gepubliceerd.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/kasper-dolberg-terug-bij-ajax/"},{"label":"Tipsbladet","url":"https://www.tipsbladet.dk/nyhed/benelux/afsloering-dolberg-paa-plads-i-ajax"}]}'::jsonb WHERE id = 'dolberg';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Red Bull Salzburg","transferType":"Definitieve transfer","fee":"€14,75 miljoen vast","terms":["Door variabelen kan de transfersom oplopen tot €17,25 miljoen."],"note":null,"sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-en-rb-salzburg-bereiken-akkoord-over-oscar-gloukh"}]}'::jsonb WHERE id = 'gloukh';
UPDATE ajax_players SET arrival_deal = '{"status":"partly_reported","updatedAt":"2026-09-08","fromClub":"Girona FC","transferType":"Definitieve transfer","fee":"Gemeld: €3,5–4 miljoen vast","terms":["Daarnaast wordt circa €1 miljoen aan variabelen gemeld."],"note":"Ajax en Girona publiceerden geen bedrag. Spaanse bronnen noemen licht verschillende vaste transfersommen.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-en-girona-fc-bereiken-akkoord-over-viktor-tsygankov"},{"label":"Cadena SER","url":"https://cadenaser.com/cataluna/2026/08/24/tygankov-i-minsu-sortiran-del-girona-sercat/"},{"label":"AS","url":"https://as.com/futbol/el-negocio-del-ajax-con-tsygankov-f202608-n/"}]}'::jsonb WHERE id = 'tsygankov';
UPDATE ajax_players SET arrival_deal = '{"status":"partly_reported","updatedAt":"2026-09-08","fromClub":"AS Monaco","transferType":"Definitieve transfer","fee":"Gemeld: circa €9–10 miljoen","terms":[],"note":"Ajax en AS Monaco maakten geen bedrag bekend; openbare berichtgeving noemt geen eenduidige exacte som.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/caio-henrique-naar-ajax/"},{"label":"AS","url":"https://as.com/futbol/internacional/jofre-torrents-cambia-el-barca-por-el-ajax-f202608-n/"}]}'::jsonb WHERE id = 'caio-henrique';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Excelsior-jeugd","transferType":"Jeugdtransfer","fee":"Niet openbaar gemaakt","terms":["Sinds 2018 in de jeugdopleiding van Ajax."],"note":"Voor jeugdtransfers worden doorgaans geen financiële details gepubliceerd.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/teams/ajax-1/youri-baas-1"}]}'::jsonb WHERE id = 'baas';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Girona FC","transferType":"Transfervrij","fee":"Geen transfersom","terms":["Blind kwam na afloop van zijn contract bij Girona terug naar Ajax."],"note":"Eventuele tekenpremies of andere persoonlijke afspraken zijn niet openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://english.ajax.nl/articles/daley-blind-returns-to-ajax/"}]}'::jsonb WHERE id = 'blind';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Internazionale","transferType":"Transfervrij","fee":"Geen transfersom","terms":[],"note":"Eventuele tekenpremies of andere persoonlijke afspraken zijn niet openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/artikelen/davy-klaassen-terug-bij-ajax/"}]}'::jsonb WHERE id = 'klaassen';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Go Ahead Eagles","transferType":"Definitieve transfer","fee":"Niet openbaar gemaakt","terms":[],"note":"Ajax heeft geen transfersom of aanvullende financiële afspraken openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/artikelen/ajax-contracteert-oliver-edvardsen"}]}'::jsonb WHERE id = 'edvardsen';
UPDATE ajax_players SET arrival_deal = '{"status":"partly_reported","updatedAt":"2026-09-08","fromClub":"FC Barcelona","transferType":"Definitieve transfer","fee":"Geen vaste som officieel gepubliceerd","terms":["Gemeld: maximaal circa €5,5–6 miljoen via variabelen.","Barcelona behoudt volgens de berichtgeving 50% bij een toekomstige verkoop.","Een terugkoopoptie wordt gemeld; de precieze voorwaarden en het bedrag verschillen per bron."],"note":"Ajax en Barcelona publiceerden geen financiële voorwaarden. Spaanse en Catalaanse bronnen beschrijven de constructie niet volledig hetzelfde.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-en-fc-barcelona-bereiken-akkoord-over-jofre-torrents/"},{"label":"FC Barcelona","url":"https://www.fcbarcelona.com/en/news/4556728/agreement-with-ajax-for-the-transfer-of-jofre-torrents/amp"},{"label":"Esport3","url":"https://www.3cat.cat/esport3/oficial-jofre-torrents-ja-es-jugador-de-lajax/noticia/3425017/"},{"label":"AS","url":"https://as.com/futbol/internacional/jofre-torrents-cambia-el-barca-por-el-ajax-f202608-n/"}]}'::jsonb WHERE id = 'jofre-torrents';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"AC Sparta Praag","transferType":"Definitieve transfer","fee":"Niet openbaar gemaakt","terms":[],"note":"Ajax heeft geen transfersom of aanvullende financiële afspraken openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/joeri-heerkens-van-sparta-praag-naar-ajax/"}]}'::jsonb WHERE id = 'heerkens';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Feyenoord","transferType":"Definitieve transfer","fee":"Niet openbaar gemaakt door Ajax","terms":[],"note":"De officiële bekendmaking bevat geen transfersom of aanvullende financiële voorwaarden.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/artikelen/ajax-rondt-transfer-berghuis-af"}]}'::jsonb WHERE id = 'berghuis';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"KAA Gent-jeugd","transferType":"Jeugdtransfer","fee":"Niet openbaar gemaakt","terms":[],"note":"Voor deze jeugdtransfer zijn geen financiële details gepubliceerd.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/artikelen/ajax-contracteert-jorthy-mokio/"}]}'::jsonb WHERE id = 'mokio';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"FC Dallas","transferType":"Definitieve transfer","fee":"Niet openbaar gemaakt","terms":[],"note":"Ajax heeft geen transfersom of aanvullende financiële afspraken openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-contracteert-maarten-paes"}]}'::jsonb WHERE id = 'paes';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Koninklijke HFC-jeugd","transferType":"Jeugdtransfer","fee":"Niet openbaar gemaakt","terms":["Sinds 2018 in de jeugdopleiding van Ajax."],"note":"Voor jeugdtransfers worden doorgaans geen financiële details gepubliceerd.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/artikelen/ajax-contracteert-aaron-bouwman/"}]}'::jsonb WHERE id = 'bouwman';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Sparta Rotterdam-jeugd","transferType":"Jeugdtransfer","fee":"Niet openbaar gemaakt","terms":["Sinds 2020 in de jeugdopleiding van Ajax."],"note":"Voor jeugdtransfers worden doorgaans geen financiële details gepubliceerd.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-verlengt-contract-dies-janse/"}]}'::jsonb WHERE id = 'dies-janse';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Al-Hilal","transferType":"Definitieve transfer","fee":"Net geen €20 miljoen","terms":[],"note":"Ajax omschrijft de transfersom als net geen €20 miljoen.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-contracteert-marcos-leonardo/"}]}'::jsonb WHERE id = 'leonardo';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"RSC Anderlecht-jeugd","transferType":"Jeugdtransfer","fee":"Niet openbaar gemaakt","terms":["Sinds 2022 in de jeugdopleiding van Ajax."],"note":"Voor deze jeugdtransfer zijn geen financiële details gepubliceerd.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/artikelen/ajax-contracteert-rayane-bounida/"}]}'::jsonb WHERE id = 'bounida';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"AVV Zeeburgia","transferType":"Jeugdtransfer","fee":"Niet van toepassing","terms":["Sinds 2016 in de jeugdopleiding van Ajax."],"note":"Er is geen publiek bekende transfersom voor deze overstap naar de jeugdopleiding.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-contracteert-abdellah-ouazane/"}]}'::jsonb WHERE id = 'ouazane';
UPDATE ajax_players SET arrival_deal = '{"status":"confirmed","updatedAt":"2026-09-08","fromClub":"Wolverhampton Wanderers","transferType":"Huur met koopoptie","fee":"Niet openbaar gemaakt","terms":["Gehuurd voor het seizoen 2026/27.","Ajax heeft een optie tot koop."],"note":"De huursom en de hoogte en voorwaarden van de koopoptie zijn niet openbaar gemaakt.","sources":[{"label":"Ajax","url":"https://www.ajax.nl/club/pers/persberichten/ajax-huurt-tolu-arokodare-van-wolverhampton-wanderers/"}]}'::jsonb WHERE id = 'arokodare';

UPDATE ajax_players SET updated_at = now() WHERE active = true AND arrival_deal IS NOT NULL;

COMMIT;
