const field=name=>document.querySelector(`[name="${name}"]`);
const matchFields={opponent:field('opponent'),competition:field('competition'),kickoffDate:field('kickoffDate'),kickoffTime:field('kickoffTime'),homeOrAway:field('homeOrAway'),seasonKey:field('seasonKey'),scheduledOpenDate:field('scheduledOpenDate'),scheduledOpenTime:field('scheduledOpenTime'),scheduledCloseDate:field('scheduledCloseDate'),scheduledCloseTime:field('scheduledCloseTime')};
const amsterdamParts=value=>Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Amsterdam',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)).filter(part=>part.type!=='literal').map(part=>[part.type,part.value]));
const setDateTime=(dateField,timeField,value)=>{if(!dateField||!timeField)return;const parts=amsterdamParts(value);dateField.value=`${parts.year}-${parts.month}-${parts.day}`;timeField.value=`${parts.hour}:${parts.minute}`};
const localDate=(dateField,timeField)=>dateField?.value&&timeField?.value?new Date(`${dateField.value}T${timeField.value}:00`):null;
const setDefaultSchedule=()=>{const kickoff=localDate(matchFields.kickoffDate,matchFields.kickoffTime);if(!kickoff||Number.isNaN(kickoff.getTime()))return;if(matchFields.scheduledOpenDate&&!matchFields.scheduledOpenDate.value)setDateTime(matchFields.scheduledOpenDate,matchFields.scheduledOpenTime,new Date(kickoff.getTime()+2*3600000));if(matchFields.scheduledCloseDate&&!matchFields.scheduledCloseDate.value)setDateTime(matchFields.scheduledCloseDate,matchFields.scheduledCloseTime,new Date(kickoff.getTime()+26*3600000))};
let seasonTouched=false;matchFields.seasonKey?.addEventListener('change',()=>{seasonTouched=true});
const setDefaultSeason=()=>{if(seasonTouched||!matchFields.seasonKey||!matchFields.kickoffDate?.value)return;const [year,month]=matchFields.kickoffDate.value.split('-').map(Number),start=month>=7?year:year-1,key=`${start}-${String(start+1).slice(-2)}`;if(![...matchFields.seasonKey.options].some(option=>option.value===key)){matchFields.seasonKey.add(new Option(key,key))}matchFields.seasonKey.value=key};
matchFields.kickoffDate?.addEventListener('change',()=>{setDefaultSchedule();setDefaultSeason()});
matchFields.kickoffTime?.addEventListener('change',setDefaultSchedule);
if(matchFields.opponent)fetch('/api/next-match').then(response=>response.ok?response.json():Promise.reject()).then(({match})=>{if(!match)return;matchFields.opponent.value=match.opponent||'';matchFields.competition.value=match.competition||'';setDateTime(matchFields.kickoffDate,matchFields.kickoffTime,match.kickoff);matchFields.homeOrAway.value=match.isHome?'home':'away';setDefaultSchedule()}).catch(()=>{});
document.querySelector('[data-copy]')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(document.querySelector('#share-url').value);document.querySelector('[data-copy]').textContent='Gekopieerd'});
document.querySelector('[data-share]')?.addEventListener('click',()=>{const shareField=document.querySelector('#share-url'),url=shareField.value,title=shareField.dataset.shareTitle,text=shareField.dataset.shareText;if(navigator.share)navigator.share({title,text,url});else navigator.clipboard.writeText(url)});
const playerInputs=[...document.querySelectorAll('.admin-player input')],playerCount=document.querySelector('[data-player-count]');
const updatePlayerCount=()=>{if(playerCount)playerCount.textContent=String(playerInputs.filter(input=>input.checked).length)};
playerInputs.forEach(input=>input.addEventListener('change',updatePlayerCount));

const livePanel=document.querySelector('[data-live-votes]');
if(livePanel){
  const total=livePanel.querySelector('[data-live-total]'),totalLabel=livePanel.querySelector('[data-live-total-label]'),list=livePanel.querySelector('[data-live-list]'),updated=livePanel.querySelector('[data-live-updated]'),message=livePanel.querySelector('[data-live-message]'),error=livePanel.querySelector('[data-live-error]'),refresh=livePanel.querySelector('[data-live-refresh]');
  let timer;
  const renderRow=player=>{const row=document.createElement('div');row.className='live-vote-row';row.dataset.playerId=player.player_id;const image=document.createElement('img');image.src=player.image_url_snapshot;image.alt='';const name=document.createElement('strong');name.textContent=player.name_snapshot;const count=document.createElement('span');count.textContent=`${player.votes} · ${player.percentage}%`;const bar=document.createElement('progress');bar.max=100;bar.value=player.percentage;bar.setAttribute('aria-hidden','true');row.append(image,name,count,bar);return row};
  const render=data=>{total.textContent=String(data.total);totalLabel.textContent=data.total===1?'stem':'stemmen';list.replaceChildren();const visible=data.players.filter(player=>player.votes>0);if(visible.length)visible.forEach(player=>list.append(renderRow(player)));else{const empty=document.createElement('p');empty.className='live-votes__empty';empty.textContent='Nog geen stemmen uitgebracht.';list.append(empty)}updated.textContent=`Bijgewerkt om ${new Intl.DateTimeFormat('nl-NL',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(data.updatedAt))}`;message.textContent=data.status==='open'?'Wordt elke 8 seconden bijgewerkt.':data.status==='closed'?'Definitieve stemverdeling.':'De stemming is nog niet geopend.';livePanel.dataset.liveStatus=data.status;if(data.status!=='open'&&timer)clearInterval(timer)};
  const load=async()=>{refresh.disabled=true;error.hidden=true;try{const response=await fetch(livePanel.dataset.liveUrl,{headers:{Accept:'application/json'},cache:'no-store'});if(!response.ok)throw new Error('LIVE_VOTES_FAILED');render(await response.json())}catch{error.hidden=false}finally{refresh.disabled=false}};
  refresh.addEventListener('click',load);
  if(livePanel.dataset.liveStatus==='open')timer=setInterval(load,8000);
}
