import { isSameOrigin, redirect, type Session } from "../../lib/discord-auth";
import { permissions } from "../../lib/permissions.config";
import { getSessionWithPermission } from "../../lib/server-permissions";
import { players } from "../../data/players";
import { db, resultsFor } from "../../lib/motm-db";
import { esc, errorPage, formatKickoff, formatMoment, matchHeading, matchTitle, page, pageHeader, remainingTime } from "../../lib/motm-view";
import { synchronizeAllMatches, synchronizeMatch } from "../../lib/motm-scheduling";
import { amsterdamFieldsToUtc, defaultSchedule, statusLabel, toAmsterdamFields, voteLabel, winnerLabel } from "../../lib/motm-rules";
import { REVISION_CONFLICT, canDeleteMatch, mayRemovePlayer, nullableScore, parseRevision, safeAuditData, validDeleteConfirmation } from "../../lib/motm-management";
import { seasonKeyFor, seasonOptions, validSeasonKey } from "../../lib/motm-season";
import { buildLiveVoteSnapshot } from "../../lib/motm-live";
import { createMotmVisualData, MOTM_VISUAL_HEIGHT, MOTM_VISUAL_TEMPLATE_URL, MOTM_VISUAL_WIDTH } from "../../lib/motm-visual";

const query = (request: Request) => new URL(request.url).searchParams;
const manager = (request: Request) => getSessionWithPermission(request, permissions.motmManage);
const activePlayers=players.filter(player=>player.active);
const slugify=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,50);
const revisionInput=(revision:number)=>`<input type="hidden" name="revision" value="${revision}">`;
const conflict=()=>errorPage("Wijzigingsconflict",REVISION_CONFLICT,409);
const dateTimeFields=(prefix:string,label:string,value:string|Date|null|undefined,help="Lokale tijd, Europe/Amsterdam")=>{const fields=toAmsterdamFields(value);return `<div class="datetime-group" role="group" aria-label="${esc(label)}"><span class="datetime-group__label">${esc(label)}</span><div class="datetime-fields"><label>Datum<input required type="date" name="${prefix}Date" value="${esc(fields.date)}"></label><label>Tijd<input required type="time" name="${prefix}Time" value="${esc(fields.time)}" step="60"></label></div><small>${esc(help)}</small></div>`};
const scheduleFields=(openValue?:string|Date|null,closeValue?:string|Date|null)=>`${dateTimeFields("scheduledOpen","Stemming opent",openValue,"Lokale tijd, Europe/Amsterdam · standaard twee uur na de aftrap")}${dateTimeFields("scheduledClose","Stemming sluit",closeValue)}`;
const dateTimeFromForm=(form:FormData,prefix:string)=>amsterdamFieldsToUtc(String(form.get(`${prefix}Date`)??""),String(form.get(`${prefix}Time`)??""));
const seasonFields=(selected:string,counts=true,reason="")=>`<label>Seizoen<select required name="seasonKey">${seasonOptions(selected).map(key=>`<option value="${esc(key)}"${key===selected?" selected":""}>${esc(key)}</option>`).join("")}</select></label><label class="season-counts"><input type="checkbox" name="countsForSeason" value="true"${counts?" checked":""}> Telt mee voor Ajacied van het Jaar</label><label>Reden voor uitsluiting<input name="seasonExclusionReason" maxlength="500" value="${esc(reason)}" placeholder="Bijvoorbeeld: oefenwedstrijd"></label>`;
const seasonFromForm=(form:FormData)=>{const seasonKey=String(form.get("seasonKey")??"").trim(),countsForSeason=form.get("countsForSeason")==="true",seasonExclusionReason=String(form.get("seasonExclusionReason")??"").trim();return validSeasonKey(seasonKey)&&seasonExclusionReason.length<=500?{seasonKey,countsForSeason,seasonExclusionReason:countsForSeason?null:seasonExclusionReason||null}:null;};
const playerPicker=()=>`<div class="selection-count"><strong data-player-count>${activePlayers.length}</strong> spelers geselecteerd</div><div class="admin-players">${activePlayers.map(p=>`<label class="admin-player"><input type="checkbox" name="players" value="${esc(p.id)}" checked><span><img src="${esc(p.imageUrl)}" alt=""><b>${esc(p.name)}</b><small>${esc(p.position)}${p.shirtNumber?` · #${p.shirtNumber}`:""}</small></span></label>`).join("")}</div>`;
const auditSummary:Record<string,string>={created:"Stemming aangemaakt",match_updated:"Wedstrijdgegevens gewijzigd",schedule_updated:"Planning gewijzigd",player_added:"Speler toegevoegd",player_updated:"Speler gecorrigeerd",player_removed:"Speler verwijderd",duplicated:"Stemming gedupliceerd",deleted:"Stemming verwijderd",restored:"Stemming hersteld",opened:"Stemming geopend",closed:"Stemming gesloten",auto_closed:"Stemming automatisch gesloten"};
const audit=async(tx:any,matchId:string,session:Session,action:string,before:Record<string,unknown>|null,after:Record<string,unknown>|null)=>tx`INSERT INTO motm_audit_log(match_id,actor_discord_user_id,actor_username_snapshot,action,before_data,after_data) VALUES(${matchId},${session.userId},${session.username},${action},${before?tx.json(safeAuditData(before)):null},${after?tx.json(safeAuditData(after)):null})`;
const actor=(row:any)=>row.actor_username_snapshot||row.actor_discord_user_id;
const scoreFor=(match:any,team:"ajax"|"opponent")=>match.home_or_away==="home"?(team==="ajax"?match.home_score:match.away_score):(team==="ajax"?match.away_score:match.home_score);
const matchSnapshot=(m:any)=>({opponent:m.opponent,competition:m.competition,kickoff_at:m.kickoff_at,home_or_away:m.home_or_away,home_score:m.home_score,away_score:m.away_score,status:m.status,scheduled_open_at:m.scheduled_open_at,scheduled_close_at:m.scheduled_close_at,season_key:m.season_key,counts_for_season:m.counts_for_season,season_exclusion_reason:m.season_exclusion_reason});
const liveVotePanel=(match:any,rows:any[],total:number)=>{const visible=rows.filter(row=>Number(row.votes)>0).sort((a,b)=>Number(b.votes)-Number(a.votes)||String(a.name_snapshot).localeCompare(String(b.name_snapshot),"nl"));return `<section class="management-section live-votes" data-live-votes data-live-status="${esc(match.status)}" data-live-url="/club/motm/beheer/${esc(match.id)}/live"><div class="live-votes__heading"><div><p class="eyebrow">Alleen voor beheer</p><h2>Live stemverloop</h2></div><div class="live-votes__total"><strong data-live-total>${total}</strong><span data-live-total-label>${total===1?"stem":"stemmen"}</span></div></div><p class="live-votes__meta"><span class="live-dot${match.status==="open"?" is-live":""}" aria-hidden="true"></span><span data-live-message>${match.status==="open"?"Live stemverloop.":match.status==="closed"?"Definitieve stemverdeling.":"De stemming is nog niet geopend."}</span> <time data-live-updated>Zojuist bijgewerkt</time></p><div class="live-votes__list" data-live-list>${visible.length?visible.map(row=>{const votes=Number(row.votes),percentage=total?Math.round(votes*100/total):0;return `<div class="live-vote-row" data-player-id="${esc(row.player_id)}"><img src="${esc(row.image_url_snapshot)}" alt=""><strong>${esc(row.name_snapshot)}</strong><span>${votes} · ${percentage}%</span><progress max="100" value="${percentage}" aria-hidden="true"></progress></div>`}).join(""):`<p class="live-votes__empty" data-live-empty>Nog geen stemmen uitgebracht.</p>`}</div><button class="button secondary live-votes__refresh" type="button" data-live-refresh>Nu verversen</button><p class="live-votes__error" data-live-error hidden>Bijwerken lukt tijdelijk niet.</p></section>`;};

async function liveVotes(id:string){
  let [match]=await db()`SELECT id,status,scheduled_open_at,scheduled_close_at FROM motm_matches WHERE id=${id} AND deleted_at IS NULL`;
  if(!match)return new Response(JSON.stringify({error:"not_found"}),{status:404,headers:{"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store"}});
  match=await synchronizeMatch(match as any);
  const rows=await db()`SELECT p.player_id,p.name_snapshot,p.image_url_snapshot,count(v.player_id)::int votes FROM motm_match_players p LEFT JOIN motm_votes v ON v.match_id=p.match_id AND v.player_id=p.player_id WHERE p.match_id=${id} GROUP BY p.player_id,p.name_snapshot,p.image_url_snapshot`;
  return new Response(JSON.stringify(buildLiveVoteSnapshot(match.status,rows.map((row:any)=>({...row,votes:Number(row.votes)})))),{headers:{"Content-Type":"application/json; charset=UTF-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});
}

async function detail(request:Request,session:Session,id:string){
  let [match]=await db()`SELECT * FROM motm_matches WHERE id=${id}`;
  if(!match)return errorPage("Niet gevonden","Deze stemming bestaat niet.",404);
  if(match.deleted_at&&!canDeleteMatch(session))return errorPage("Niet gevonden","Deze stemming bestaat niet.",404);
  if(!match.deleted_at)match=await synchronizeMatch(match as any);
  const [{count}]=await db()`SELECT count(*)::int count FROM motm_votes WHERE match_id=${id}`;
  const matchPlayers=await db()`SELECT p.*,(SELECT count(*)::int FROM motm_votes v WHERE v.match_id=p.match_id AND v.player_id=p.player_id) votes FROM motm_match_players p WHERE p.match_id=${id} ORDER BY p.shirt_number_snapshot NULLS LAST,p.name_snapshot`;
  const logs=await db()`SELECT * FROM motm_audit_log WHERE match_id=${id} ORDER BY created_at DESC LIMIT 20`;
  const results=match.status==="closed"?await resultsFor(id):[],winners=results.filter(row=>row.rank===1),deleteAllowed=canDeleteMatch(session),revision=Number(match.revision);
  const matchForm=!match.deleted_at?`<section class="management-section"><h2>1. Wedstrijdgegevens</h2><form method="post">${revisionInput(revision)}<input type="hidden" name="intent" value="update-match"><div class="form-grid"><label>Tegenstander<input required name="opponent" value="${esc(match.opponent)}"></label><label>Competitie<input required name="competition" value="${esc(match.competition)}"></label>${dateTimeFields("kickoff","Aftrap",match.kickoff_at)}<label>Thuis of uit<select name="homeOrAway"><option value="home"${match.home_or_away==="home"?" selected":""}>Thuis</option><option value="away"${match.home_or_away==="away"?" selected":""}>Uit</option></select></label>${seasonFields(match.season_key,match.counts_for_season,match.season_exclusion_reason??"")}<label>Doelpunten Ajax<input min="0" max="99" type="number" name="ajaxScore" value="${scoreFor(match,"ajax")??""}"></label><label>Doelpunten tegenstander<input min="0" max="99" type="number" name="opponentScore" value="${scoreFor(match,"opponent")??""}"></label></div><p class="help">De bestaande slug en het gekozen seizoen blijven behouden totdat je dit formulier opslaat.</p><button class="button" type="submit">Wedstrijd opslaan</button></form></section>`:"";
  const statusAction=match.status==="draft"?`<form method="post">${revisionInput(revision)}<button class="button secondary" name="intent" value="open">Direct openen</button></form>`:match.status==="open"?`<form method="post">${revisionInput(revision)}<button class="button danger" name="intent" value="close">Direct sluiten</button></form>`:"";
  const editableSchedule=match.status==="open"?dateTimeFields("scheduledClose","Stemming sluit",match.scheduled_close_at):scheduleFields(match.scheduled_open_at,match.scheduled_close_at);
  const planning=match.deleted_at?"":`<section class="management-section"><h2>2. Planning en status</h2>${match.status==="closed"?`<p>Een gesloten stemming kan niet worden heropend.</p>`:`<form method="post">${revisionInput(revision)}<input type="hidden" name="intent" value="update-schedule"><div class="form-grid">${editableSchedule}</div><button class="button" type="submit">Planning opslaan</button></form>`}${match.status==="open"?`<p>Resterend: <strong>${esc(remainingTime(match.scheduled_close_at))}</strong></p>`:""}${statusAction}</section>`;
  const playerRows=matchPlayers.map((p:any)=>`<div class="managed-player"><form method="post">${revisionInput(revision)}<input type="hidden" name="intent" value="update-player"><input type="hidden" name="playerId" value="${esc(p.player_id)}"><div class="form-grid"><label>Naam<input required name="name" value="${esc(p.name_snapshot)}"></label><label>Rugnummer<input type="number" min="0" max="99" name="shirtNumber" value="${p.shirt_number_snapshot??""}"></label><label>Positie<input required name="position" value="${esc(p.position_snapshot)}"></label><label>Foto<input required name="imageUrl" value="${esc(p.image_url_snapshot)}"></label></div><button class="button secondary">Correctie opslaan</button></form>${mayRemovePlayer(match.status,Number(p.votes),deleteAllowed)?`<form method="post">${revisionInput(revision)}<input type="hidden" name="intent" value="remove-player"><input type="hidden" name="playerId" value="${esc(p.player_id)}"><button class="button danger">Speler verwijderen</button></form>`:`<small>${p.votes?`${voteLabel(Number(p.votes))}; verwijderen is geblokkeerd.`:match.status!=="draft"?"Alleen Admin/Owner mag na opening verwijderen.":""}</small>`}</div>`).join("");
  const available=activePlayers.filter(p=>!matchPlayers.some((mp:any)=>mp.player_id===p.id));
  const addPlayer=!match.deleted_at&&match.status==="draft"&&available.length?`<form method="post" class="add-player">${revisionInput(revision)}<input type="hidden" name="intent" value="add-player"><label>Speler toevoegen<select name="playerId">${available.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join("")}</select></label><button class="button secondary">Toevoegen</button></form>`:"";
  const playersSection=!match.deleted_at?`<section class="management-section player-management"><h2>3. Spelers</h2><p>${matchPlayers.length} spelers gekoppeld aan deze stemming. Open dit alleen voor een correctie.</p><details class="player-editor"><summary><span>Bewerk spelers</span><small>${matchPlayers.length} spelers</small></summary><div class="player-editor__body">${addPlayer}<div class="managed-players">${playerRows}</div></div></details></section>`:"";
  const visualWinner=winners[0],visualPlayer=visualWinner?matchPlayers.find((player:any)=>player.player_id===visualWinner.player_id):undefined;
  const visual=createMotmVisualData({status:match.status,slug:match.slug,opponent:match.opponent,homeOrAway:match.home_or_away,shirtNumber:visualPlayer?.shirt_number_snapshot??null,winner:visualWinner});
  const winnerVisual=visual?`<div class="admin-winner-visual" data-winner-visual data-template-url="${MOTM_VISUAL_TEMPLATE_URL}" data-match-title="${esc(visual.matchTitle)}" data-first-name="${esc(visual.firstName)}" data-last-name="${esc(visual.lastName)}" data-shirt-number="${visual.shirtNumber}" data-percentage="${visual.percentage}" data-player-id="${esc(visual.playerId)}" data-player-image="${esc(visual.playerImageUrl)}" data-filename="${esc(visual.filename)}"><figure class="winner-visual-frame"><canvas width="${MOTM_VISUAL_WIDTH}" height="${MOTM_VISUAL_HEIGHT}" aria-label="Man of the Match-resultaatvisual voor ${esc(visual.firstName)} ${esc(visual.lastName)}"></canvas><figcaption data-visual-status>Template, lettertypen en spelersfoto laden…</figcaption></figure><button class="button secondary" type="button" data-download-visual disabled>Download PNG</button></div>`:"";
  const share=`<section class="management-section share-primary"><p class="eyebrow">Direct gebruiken</p><h2>Stemlink delen</h2><p>Dit is de openbare link die je na het aanmaken met leden deelt.</p>${winnerVisual}<label>Openbare stemlink<input id="share-url" readonly value="${esc(new URL(`/stem/${match.slug}`,request.url).href)}"></label>${match.deleted_at?`<p>Deze link is niet beschikbaar zolang de stemming verwijderd is.</p>`:`<div class="share-actions"><button class="button" type="button" data-copy>Kopieer stemlink</button><a class="button secondary" href="/stem/${esc(match.slug)}">Bekijk stempagina</a></div>`}</section>`;
  const danger=deleteAllowed?`<section class="management-section removal-section"><h2>4. Stemming verwijderen</h2>${match.deleted_at?`<p>Verwijderd ${esc(formatMoment(match.deleted_at))} door ${esc(match.deleted_by_discord_user_id??"onbekend")}.</p><form method="post">${revisionInput(revision)}<input type="hidden" name="intent" value="restore"><button class="button secondary">Stemming herstellen</button></form>`:`<p>Verwijder deze stemming uit het overzicht. Je kunt hem later nog herstellen.</p><form method="post">${revisionInput(revision)}<input type="hidden" name="intent" value="delete"><input type="hidden" name="reason" value="Handmatig verwijderd"><input type="hidden" name="confirmation" value="VERWIJDEREN"><button class="button secondary">Verwijderen</button></form>`}</section>`:"";
  const logHtml=`<section class="management-section"><h2>5. Wijzigingslog</h2>${logs.length?`<ol class="audit-log">${logs.map((row:any)=>`<li><time>${esc(formatMoment(row.created_at))}</time><strong>${esc(auditSummary[row.action]??row.action)}</strong><span>${esc(actor(row))}</span>${row.after_data?.summary?`<small>${esc(String(row.after_data.summary))}</small>`:""}</li>`).join("")}</ol>`:"<p>Nog geen wijzigingen vastgelegd.</p>"}</section>`;
  const winner=match.status==="closed"&&winners.length?` · ${winnerLabel(winners.length)}: ${esc(winners.map(row=>row.name_snapshot).join(" & "))}`:"";
  const actions=!match.deleted_at?`<form method="post" class="inline-action">${revisionInput(revision)}<button class="button secondary" name="intent" value="duplicate">Stemming dupliceren</button></form>`:"";
  return page("Stemming beheren",`<main class="motm-main admin">${pageHeader("Wedstrijdbeheer","MOTM-beheer","/club/motm/beheer","Beheer",actions)}<section class="match-head"><span class="status status-${match.deleted_at?"deleted":match.status}">${match.deleted_at?"Verwijderd":statusLabel(match.status)}</span>${matchHeading(match)}<p>${voteLabel(Number(count))} · ${matchPlayers.length} spelers${winner}</p></section>${share}${!match.deleted_at?liveVotePanel(match,matchPlayers,Number(count)):""}${matchForm}${planning}${playersSection}${danger}${logHtml}</main>`,"/motm-admin.js",session);
}

export async function GET(request:Request){
  const session=await manager(request);if(!session)return errorPage("Geen beheerrecht","Je hebt motm.manage nodig om stemmingen te beheren.",403);
  const view=query(request).get("view")??"list",id=query(request).get("id");
  try{
    await synchronizeAllMatches();
    if(view==="live"&&id)return liveVotes(id);
    if(view==="new"){const defaultSeason=seasonKeyFor(new Date());return page("Nieuwe stemming",`<main class="motm-main admin new-poll">${pageHeader("Nieuwe stemming","MOTM-beheer","/club/motm/beheer","Beheer")}<form method="post" action="/club/motm/nieuw"><fieldset><legend><span>1</span> Wedstrijd</legend><div class="form-grid"><label>Tegenstander<input required name="opponent"></label><label>Competitie<input required name="competition" value="Eredivisie"></label>${dateTimeFields("kickoff","Aftrap",null)}<label>Thuis of uit<select name="homeOrAway"><option value="home">Thuis</option><option value="away">Uit</option></select></label>${seasonFields(defaultSeason)}<label>Doelpunten Ajax<input min="0" max="99" type="number" name="ajaxScore"></label><label>Doelpunten tegenstander<input min="0" max="99" type="number" name="opponentScore"></label></div></fieldset><fieldset><legend><span>2</span> Planning</legend><div class="form-grid">${scheduleFields()}</div></fieldset><fieldset><legend><span>3</span> Spelers</legend>${playerPicker()}</fieldset><fieldset><legend><span>4</span> Afronden</legend><div class="admin-actions"><button class="button secondary" name="intent" value="draft">Opslaan als concept</button><button class="button" name="intent" value="open">Direct openen</button></div></fieldset></form></main>`,"/motm-admin.js",session);}
    if(id)return detail(request,session,id);
    const term=(query(request).get("q")??"").trim();
    const includeDeleted=canDeleteMatch(session);const matches=await db()`SELECT m.*,(SELECT count(*)::int FROM motm_votes v WHERE v.match_id=m.id) votes FROM motm_matches m WHERE (${includeDeleted} OR m.deleted_at IS NULL) AND (${term}='' OR m.opponent ILIKE ${`%${term}%`} OR m.competition ILIKE ${`%${term}%`}) ORDER BY m.created_at DESC LIMIT 100`;
    const visible=matches.filter((m:any)=>!m.deleted_at),deleted=matches.filter((m:any)=>m.deleted_at),groups=[{title:"Actief",items:visible.filter((m:any)=>m.status==="open")},{title:"Gepland",items:visible.filter((m:any)=>m.status==="draft"&&m.scheduled_open_at)},{title:"Concepten",items:visible.filter((m:any)=>m.status==="draft"&&!m.scheduled_open_at)},{title:"Gesloten",items:visible.filter((m:any)=>m.status==="closed")}];if(canDeleteMatch(session))groups.push({title:"Verwijderd",items:deleted});
    const html=groups.map(group=>`<section class="manage-group"><div class="section-heading"><h2>${group.title}</h2><span>${group.items.length}</span></div>${group.items.length?`<div class="manage-list">${group.items.map((m:any)=>`<a href="/club/motm/beheer/${m.id}"><span class="status status-${m.deleted_at?"deleted":m.status}">${group.title}</span><span><strong>${esc(m.opponent)}</strong><small>${esc(m.competition)} · ${esc(formatKickoff(m.kickoff_at))} · ${voteLabel(Number(m.votes))}${m.deleted_at?` · ${esc(formatMoment(m.deleted_at))}`:""}</small></span><b>Beheren →</b></a>`).join("")}</div>`:`<p class="group-empty">Geen stemmingen</p>`}</section>`).join("");
    return page("MOTM-beheer",`<main class="motm-main admin">${pageHeader("MOTM-beheer","AjaxPro staf","/club/motm","Stemmen",'<a class="button" href="/club/motm/nieuw">Nieuwe stemming</a>')}<form method="get" class="management-search"><label>Zoek op tegenstander of competitie<input name="q" value="${esc(term)}"></label><button class="button secondary">Zoeken</button></form>${html}</main>`,"",session);
  }catch(error){console.error("MOTM admin failed",error);return errorPage("Database niet beschikbaar","Controleer of migratie 004 op deze omgeving is uitgevoerd.",503);}
}

export async function POST(request:Request){
  if(!isSameOrigin(request))return errorPage("Ongeldige aanvraag","Ververs de pagina.",403);
  const session=await manager(request);if(!session)return errorPage("Geen beheerrecht","Je hebt motm.manage nodig.",403);
  const id=query(request).get("id"),form=await request.formData(),intent=String(form.get("intent")??"");
  try{
    if(!id)return createMatch(form,intent,session);
    let [match]=await db()`SELECT * FROM motm_matches WHERE id=${id}`;if(!match)return errorPage("Niet gevonden","Deze stemming bestaat niet.",404);
    if(!match.deleted_at)match=await synchronizeMatch(match as any);
    const revision=parseRevision(form.get("revision"));if(!revision||revision!==Number(match.revision))return conflict();
    const sql=db();
    if(intent==="delete"||intent==="restore"){
      if(!canDeleteMatch(session))return errorPage("Geen verwijderrecht","Alleen Owner en Admin mogen verwijderen of herstellen.",403);
      if(intent==="delete"){
        const reason=String(form.get("reason")??"").trim(),confirmation=String(form.get("confirmation")??"");if(match.deleted_at||reason.length<3||reason.length>500||!validDeleteConfirmation(confirmation,match.opponent))return errorPage("Verwijderen niet bevestigd","Geef een reden en typ de tegenstander of VERWIJDEREN.");
        const done=await sql.begin(async tx=>{const [updated]=await tx`UPDATE motm_matches SET deleted_at=now(),deleted_by_discord_user_id=${session.userId},delete_reason=${reason},revision=revision+1 WHERE id=${id} AND revision=${revision} AND deleted_at IS NULL RETURNING *`;if(!updated)return null;await audit(tx,id,session,"deleted",{status:match.status},{status:match.status,reason,summary:`Reden: ${reason}`});return updated;});if(!done)return conflict();return redirect("/club/motm/beheer?deleted=1");
      }
      const done=await sql.begin(async tx=>{const [updated]=await tx`UPDATE motm_matches SET deleted_at=NULL,deleted_by_discord_user_id=NULL,delete_reason=NULL,revision=revision+1 WHERE id=${id} AND revision=${revision} AND deleted_at IS NOT NULL RETURNING *`;if(!updated)return null;await audit(tx,id,session,"restored",{status:match.status,reason:match.delete_reason},{status:match.status});return updated;});if(!done)return conflict();await synchronizeMatch(done as any);return redirect(`/club/motm/beheer/${id}`);
    }
    if(match.deleted_at)return errorPage("Stemming verwijderd","Herstel de stemming voordat je andere wijzigingen uitvoert.",409);
    if(intent==="duplicate")return duplicateMatch(match,revision,session);
    if(intent==="open"||intent==="close"){
      const expected=intent==="open"?"draft":"open",next=intent==="open"?"open":"closed",action=intent==="open"?"opened":"closed";
      if(match.status!==expected)return errorPage("Ongeldige statusovergang","Een gesloten stemming kan niet worden heropend.",409);
      const now=new Date(),done=await sql.begin(async tx=>{const [updated]=await tx`UPDATE motm_matches SET status=${next},opened_at=CASE WHEN ${next}='open' THEN COALESCE(opened_at,${now}) ELSE opened_at END,closed_at=CASE WHEN ${next}='closed' THEN ${now} ELSE closed_at END,revision=revision+1 WHERE id=${id} AND revision=${revision} AND status=${expected} AND deleted_at IS NULL RETURNING *`;if(!updated)return null;await audit(tx,id,session,action,{status:expected},{status:next});return updated;});if(!done)return conflict();return redirect(`/club/motm/beheer/${id}`);
    }
    if(intent==="update-match"){
      const opponent=String(form.get("opponent")??"").trim(),competition=String(form.get("competition")??"").trim(),homeOrAway=String(form.get("homeOrAway")??""),kickoff=dateTimeFromForm(form,"kickoff"),ajaxScore=nullableScore(form.get("ajaxScore")),opponentScore=nullableScore(form.get("opponentScore")),seasonData=seasonFromForm(form);if(!opponent||!competition||!kickoff||!["home","away"].includes(homeOrAway)||ajaxScore===undefined||opponentScore===undefined||!seasonData)return errorPage("Controleer de wedstrijdgegevens","Vul geldige wedstrijdgegevens, seizoen en scores in.");const homeScore=homeOrAway==="home"?ajaxScore:opponentScore,awayScore=homeOrAway==="home"?opponentScore:ajaxScore,before=matchSnapshot(match);const done=await sql.begin(async tx=>{const [updated]=await tx`UPDATE motm_matches SET opponent=${opponent},competition=${competition},kickoff_at=${kickoff},home_or_away=${homeOrAway},home_score=${homeScore},away_score=${awayScore},season_key=${seasonData.seasonKey},counts_for_season=${seasonData.countsForSeason},season_exclusion_reason=${seasonData.seasonExclusionReason},revision=revision+1 WHERE id=${id} AND revision=${revision} AND deleted_at IS NULL RETURNING *`;if(!updated)return null;await audit(tx,id,session,"match_updated",before,matchSnapshot(updated));return updated;});if(!done)return conflict();return redirect(`/club/motm/beheer/${id}`);
    }
    if(intent==="update-schedule"){
      if(match.status==="closed")return errorPage("Planning vergrendeld","Een gesloten stemming kan niet worden heropend.",409);const openAt=match.status==="open"?new Date(match.scheduled_open_at):dateTimeFromForm(form,"scheduledOpen"),closeAt=dateTimeFromForm(form,"scheduledClose");if(!openAt||!closeAt||closeAt<=openAt)return errorPage("Controleer de planning","De sluiting moet na de opening liggen.");const now=new Date(),closeNow=match.status==="open"&&closeAt<=now;const done=await sql.begin(async tx=>{const [updated]=await tx`UPDATE motm_matches SET scheduled_open_at=${openAt},scheduled_close_at=${closeAt},status=CASE WHEN ${closeNow} THEN 'closed' ELSE status END,closed_at=CASE WHEN ${closeNow} THEN ${now} ELSE closed_at END,revision=revision+1 WHERE id=${id} AND revision=${revision} AND status<>'closed' AND deleted_at IS NULL RETURNING *`;if(!updated)return null;await audit(tx,id,session,"schedule_updated",{scheduled_open_at:match.scheduled_open_at,scheduled_close_at:match.scheduled_close_at},{scheduled_open_at:openAt,scheduled_close_at:closeAt});if(closeNow)await audit(tx,id,session,"auto_closed",{status:"open"},{status:"closed"});return updated;});if(!done)return conflict();return redirect(`/club/motm/beheer/${id}`);
    }
    if(intent==="add-player"){
      if(match.status!=="draft")return errorPage("Speler niet toegevoegd","Alleen aan een concept kan een speler worden toegevoegd.",409);const selected=activePlayers.find(p=>p.id===String(form.get("playerId")??""));if(!selected)return errorPage("Ongeldige speler","Kies een speler uit de spelersbron.");const done=await sql.begin(async tx=>{const [updated]=await tx`UPDATE motm_matches SET revision=revision+1 WHERE id=${id} AND revision=${revision} AND deleted_at IS NULL RETURNING *`;if(!updated)return null;await tx`INSERT INTO motm_match_players(match_id,player_id,name_snapshot,shirt_number_snapshot,position_snapshot,image_url_snapshot) VALUES(${id},${selected.id},${selected.name},${selected.shirtNumber},${selected.position},${selected.imageUrl})`;await audit(tx,id,session,"player_added",null,{player_id:selected.id,summary:selected.name});return updated;});if(!done)return conflict();return redirect(`/club/motm/beheer/${id}`);
    }
    const playerId=String(form.get("playerId")??""),[player]=await db()`SELECT p.*,(SELECT count(*)::int FROM motm_votes v WHERE v.match_id=p.match_id AND v.player_id=p.player_id) votes FROM motm_match_players p WHERE p.match_id=${id} AND p.player_id=${playerId}`;if(!player)return errorPage("Speler niet gevonden","Ververs de pagina.",404);
    if(intent==="update-player"){
      const name=String(form.get("name")??"").trim(),position=String(form.get("position")??"").trim(),imageUrl=String(form.get("imageUrl")??"").trim(),shirtRaw=String(form.get("shirtNumber")??"").trim(),shirt=shirtRaw===""?null:Number(shirtRaw);if(!name||!position||!imageUrl||!/^\/(?!\/)|^https:\/\//.test(imageUrl)||(shirt!==null&&(!Number.isInteger(shirt)||shirt<0||shirt>99)))return errorPage("Controleer de speler","Vul geldige snapshotgegevens in.");const done=await sql.begin(async tx=>{const [updated]=await tx`UPDATE motm_matches SET revision=revision+1 WHERE id=${id} AND revision=${revision} AND deleted_at IS NULL RETURNING *`;if(!updated)return null;await tx`UPDATE motm_match_players SET name_snapshot=${name},shirt_number_snapshot=${shirt},position_snapshot=${position},image_url_snapshot=${imageUrl} WHERE match_id=${id} AND player_id=${playerId}`;await audit(tx,id,session,"player_updated",{player_id:playerId,name:player.name_snapshot,shirt_number:player.shirt_number_snapshot,position:player.position_snapshot,image_url:player.image_url_snapshot},{player_id:playerId,name,shirt_number:shirt,position,image_url:imageUrl,summary:name});return updated;});if(!done)return conflict();return redirect(`/club/motm/beheer/${id}`);
    }
    if(intent==="remove-player"){
      if(!mayRemovePlayer(match.status,Number(player.votes),canDeleteMatch(session)))return errorPage("Speler niet verwijderd",Number(player.votes)>0?"Deze speler heeft stemmen; verwijderen is nooit toegestaan.":"Alleen Owner en Admin mogen na opening een speler verwijderen.",409);const done=await sql.begin(async tx=>{const [updated]=await tx`UPDATE motm_matches SET revision=revision+1 WHERE id=${id} AND revision=${revision} AND deleted_at IS NULL RETURNING *`;if(!updated)return null;const [removed]=await tx`DELETE FROM motm_match_players WHERE match_id=${id} AND player_id=${playerId} AND NOT EXISTS(SELECT 1 FROM motm_votes WHERE match_id=${id} AND player_id=${playerId}) RETURNING player_id`;if(!removed)throw new Error("PLAYER_HAS_VOTES");await audit(tx,id,session,"player_removed",{player_id:playerId,name:player.name_snapshot},null);return updated;});if(!done)return conflict();return redirect(`/club/motm/beheer/${id}`);
    }
    return errorPage("Ongeldige actie","Deze beheeractie bestaat niet.",400);
  }catch(error){if(error instanceof Error&&error.message==="PLAYER_HAS_VOTES")return errorPage("Speler niet verwijderd","Deze speler heeft stemmen; verwijderen is nooit toegestaan.",409);console.error("MOTM mutation failed",error);return errorPage("Opslaan mislukt","Controleer of migratie 004 is uitgevoerd en probeer opnieuw.",503);}
}

async function createMatch(form:FormData,intent:string,session:Session){
  if(!["draft","open"].includes(intent))return errorPage("Ongeldige actie","Kies concept of direct openen.");const opponent=String(form.get("opponent")??"").trim(),competition=String(form.get("competition")??"").trim(),homeOrAway=String(form.get("homeOrAway")??""),kickoff=dateTimeFromForm(form,"kickoff"),seasonData=seasonFromForm(form);if(!kickoff)return errorPage("Controleer de aftrap","Gebruik een geldige Nederlandse datum en tijd.");const defaults=defaultSchedule(kickoff),scheduledOpen=dateTimeFromForm(form,"scheduledOpen")??defaults.openAt,scheduledClose=dateTimeFromForm(form,"scheduledClose")??defaults.closeAt,selected=[...new Set(form.getAll("players").map(String))],selectedPlayers=activePlayers.filter(p=>selected.includes(p.id)),ajaxScore=nullableScore(form.get("ajaxScore")),opponentScore=nullableScore(form.get("opponentScore"));if(!opponent||!competition||!seasonData||!["home","away"].includes(homeOrAway)||scheduledClose<=scheduledOpen||!selectedPlayers.length||ajaxScore===undefined||opponentScore===undefined)return errorPage("Controleer de invoer","Vul wedstrijd, seizoen, planning en minimaal één speler geldig in.");const homeScore=homeOrAway==="home"?ajaxScore:opponentScore,awayScore=homeOrAway==="home"?opponentScore:ajaxScore,slug=`${slugify(opponent)}-${kickoff.toISOString().slice(0,10)}-${crypto.randomUUID().slice(0,6)}`,sql=db();const created=await sql.begin(async tx=>{const [m]=await tx`INSERT INTO motm_matches(slug,opponent,competition,kickoff_at,home_or_away,home_score,away_score,season,season_key,counts_for_season,season_exclusion_reason,status,created_by_discord_user_id,opened_at,scheduled_open_at,scheduled_close_at) VALUES(${slug},${opponent},${competition},${kickoff},${homeOrAway},${homeScore},${awayScore},${seasonData.seasonKey},${seasonData.seasonKey},${seasonData.countsForSeason},${seasonData.seasonExclusionReason},${intent},${session.userId},${intent==="open"?new Date():null},${scheduledOpen},${scheduledClose}) RETURNING *`;for(const p of selectedPlayers)await tx`INSERT INTO motm_match_players(match_id,player_id,name_snapshot,shirt_number_snapshot,position_snapshot,image_url_snapshot) VALUES(${m.id},${p.id},${p.name},${p.shirtNumber},${p.position},${p.imageUrl})`;await audit(tx,m.id,session,"created",null,{status:intent,season_key:seasonData.seasonKey,counts_for_season:seasonData.countsForSeason,summary:`${opponent} · ${competition}`});return m;});return redirect(`/club/motm/beheer/${created.id}`);
}

async function duplicateMatch(match:any,revision:number,session:Session){
  const sql=db(),slug=`${slugify(match.opponent)}-${new Date(match.kickoff_at).toISOString().slice(0,10)}-${crypto.randomUUID().slice(0,6)}`;
  const created=await sql.begin(async tx=>{const [locked]=await tx`UPDATE motm_matches SET revision=revision+1 WHERE id=${match.id} AND revision=${revision} AND deleted_at IS NULL RETURNING *`;if(!locked)return null;const [copy]=await tx`INSERT INTO motm_matches(slug,opponent,competition,kickoff_at,home_or_away,home_score,away_score,season,season_key,counts_for_season,season_exclusion_reason,status,created_by_discord_user_id,scheduled_open_at,scheduled_close_at) VALUES(${slug},${match.opponent},${match.competition},${match.kickoff_at},${match.home_or_away},${match.home_score},${match.away_score},${match.season},${match.season_key},${match.counts_for_season},${match.season_exclusion_reason},'draft',${session.userId},NULL,NULL) RETURNING *`;await tx`INSERT INTO motm_match_players(match_id,player_id,name_snapshot,shirt_number_snapshot,position_snapshot,image_url_snapshot) SELECT ${copy.id},player_id,name_snapshot,shirt_number_snapshot,position_snapshot,image_url_snapshot FROM motm_match_players WHERE match_id=${match.id}`;await audit(tx,copy.id,session,"duplicated",null,{source_match_id:match.id,season_key:match.season_key,counts_for_season:match.counts_for_season,summary:`Kopie van ${match.opponent}`});await audit(tx,match.id,session,"duplicated",null,{new_match_id:copy.id,summary:`Gedupliceerd naar ${copy.slug}`});return copy;});return created?redirect(`/club/motm/beheer/${created.id}`):conflict();
}
