import { redirect } from "../../lib/discord-auth";
import { permissions } from "../../lib/permissions.config";
import { getSessionWithPermission } from "../../lib/server-permissions";
import { db } from "../../lib/motm-db";
import { buildSeasonStandings, seasonKeyFor, type SeasonMatch, validSeasonKey } from "../../lib/motm-season";
import { esc, errorPage, formatKickoff, matchTitle, page, pageHeader } from "../../lib/motm-view";
import { voteLabel } from "../../lib/motm-rules";
import { synchronizeAllMatches } from "../../lib/motm-scheduling";

const playerRow=(row:any)=>({player_id:String(row.player_id),name_snapshot:String(row.name_snapshot),image_url_snapshot:String(row.image_url_snapshot),votes:Number(row.votes)});
const podiumCard=(row:any)=>`<article class="standing-podium__card standing-podium__card--${row.position}"><span class="standing-position">${row.position}</span><img src="${esc(row.image_url_snapshot)}" alt=""><div><strong>${esc(row.name_snapshot)}</strong><span>${row.points} punten</span><small>${row.firsts} ${row.firsts===1?"MOTM-overwinning":"MOTM-overwinningen"}</small></div></article>`;

export async function GET(request:Request){
  const session=await getSessionWithPermission(request,permissions.portalAccess);if(!session)return redirect("/api/auth/discord-login?returnTo=/club/stand");
  const requested=new URL(request.url).searchParams.get("season"),season=requested??seasonKeyFor(new Date());if(!validSeasonKey(season))return errorPage("Ongeldig seizoen","Kies een geldig seizoen, bijvoorbeeld 2026-27.",400,session,"/club/stand","stand");
  try{
    await synchronizeAllMatches();
    const seasonRows=await db()`SELECT DISTINCT season_key FROM motm_matches WHERE deleted_at IS NULL ORDER BY season_key DESC`;
    const rows=await db()`SELECT m.id,m.slug,m.opponent,m.competition,m.kickoff_at,m.home_or_away,m.counts_for_season,p.player_id,p.name_snapshot,p.image_url_snapshot,count(v.player_id)::int votes FROM motm_matches m LEFT JOIN motm_match_players p ON p.match_id=m.id LEFT JOIN motm_votes v ON v.match_id=p.match_id AND v.player_id=p.player_id WHERE m.season_key=${season} AND m.status='closed' AND m.deleted_at IS NULL GROUP BY m.id,p.player_id,p.name_snapshot,p.image_url_snapshot ORDER BY m.kickoff_at DESC,p.name_snapshot`;
    const grouped=new Map<string,SeasonMatch>();for(const row of rows){let match=grouped.get(row.id);if(!match){match={id:row.id,slug:row.slug,opponent:row.opponent,competition:row.competition,kickoff_at:row.kickoff_at,home_or_away:row.home_or_away,counts_for_season:Boolean(row.counts_for_season),players:[]};grouped.set(row.id,match)}if(row.player_id)match.players.push(playerRow(row))}
    const matches=[...grouped.values()],{standings,rounds}=buildSeasonStandings(matches),included=matches.filter(m=>m.counts_for_season),totalVotes=included.reduce((sum,m)=>sum+m.players.reduce((n,p)=>n+p.votes,0),0),leader=standings[0];
    const seasons=[...new Set([season,...seasonRows.map((row:any)=>String(row.season_key))])];
    const selector=`<form class="season-selector" method="get"><label for="season">Seizoen</label><select id="season" name="season">${seasons.map(key=>`<option value="${esc(key)}"${key===season?" selected":""}>${esc(key)}</option>`).join("")}</select><noscript><button class="button secondary">Tonen</button></noscript></form>`;
    const stats=`<section class="season-stats" aria-label="Seizoenssamenvatting"><div><strong>${included.length}</strong><span>Meetellende wedstrijden</span></div><div><strong>${totalVotes}</strong><span>Uitgebrachte stemmen</span></div><div><strong>${standings.length}</strong><span>Spelers met punten</span></div><div><strong>${esc(leader?.name_snapshot??"—")}</strong><span>Huidige koploper</span></div></section>`;
    const empty=`<section class="empty"><h2>Nog geen stand</h2><p>Er is nog geen seizoenstand. Na de eerste gesloten MOTM-stemming verschijnt de ranglijst hier.</p></section>`;
    const podium=standings.length?`<section class="standing-podium" aria-label="Top drie">${standings.slice(0,3).map(podiumCard).join("")}</section>`:"";
    const table=standings.length?`<section class="standing-section"><div class="section-heading"><h2>Volledige stand</h2></div><div class="standing-table"><div class="standing-table__head"><span>#</span><span>Speler</span><span>Punten</span><span>1 / 2 / 3</span><span>Stemmen</span></div>${standings.map(row=>`<div class="standing-table__row"><b>${row.position}</b><span class="standing-player"><img src="${esc(row.image_url_snapshot)}" alt=""><strong>${esc(row.name_snapshot)}</strong></span><strong>${row.points}</strong><span>${row.firsts} / ${row.seconds} / ${row.thirds}</span><span>${row.votes}</span></div>`).join("")}</div></section>`:"";
    const latest=rounds.find(round=>round.match.counts_for_season&&round.results.length);const lastRound=latest?`<section class="last-round"><p class="eyebrow">Laatste ronde</p><h2>${esc(matchTitle(latest.match))}</h2><div>${latest.results.map(row=>`<span><b>${row.rank}</b> ${esc(row.name_snapshot)} <strong>+${row.rank===1?5:row.rank===2?3:1}</strong></span>`).join("")}</div></section>`:"";
    const fixtures=`<section class="season-matches"><div class="section-heading"><h2>Wedstrijden dit seizoen</h2><span>${matches.length}</span></div>${matches.length?`<div class="season-match-list">${rounds.map(({match,results})=>{const total=match.players.reduce((sum,p)=>sum+p.votes,0),winners=results.filter(r=>r.rank===1);return `<article class="season-match"><div><small>${esc(formatKickoff(match.kickoff_at))} · ${match.home_or_away==="home"?"Thuis":"Uit"}</small><h3>${esc(matchTitle(match))}</h3><p>${esc(match.competition)}</p></div><div class="season-match__result"><strong>${winners.length?esc(winners.map(w=>w.name_snapshot).join(" & ")):"Geen stemmen"}</strong><small>${results.length?results.map(r=>`${r.rank}. ${esc(r.name_snapshot)} (${r.votes})`).join(" · "):"Geen top drie"}</small><span>${esc(voteLabel(total))}</span>${match.counts_for_season?`<em>Telt mee voor de stand</em>`:`<em class="excluded">Telt niet mee voor de stand</em>`}</div><a href="/club/stemmen/${esc(match.slug)}">Bekijk uitslag →</a></article>`}).join("")}</div>`:`<p class="group-empty">Nog geen gesloten wedstrijden in dit seizoen.</p>`}</section>`;
    return page("Ajacied van het Jaar",`<main class="motm-main standings-main">${pageHeader("Ajacied van het Jaar","AjaxPro Club",undefined,undefined,selector)}<p class="page-intro">Per wedstrijd krijgt de top drie 5, 3 en 1 punt. Bij een gedeelde positie ontvangt iedere speler de volledige punten.</p>${stats}${standings.length?podium+table:empty}${lastRound}${fixtures}</main>`,"",session,"stand");
  }catch(error){console.error("Season standings failed",error);return errorPage("Stand niet beschikbaar","Controleer of migratie 004 is uitgevoerd en probeer opnieuw.",503,session,"/club","stand");}
}
