import { esc, formatKickoff, matchTitle } from "./motm-view";

export type PublicMatch={slug:string;opponent:string;competition:string;kickoff_at:string|Date;home_or_away:"home"|"away";status:"draft"|"open"|"closed"};
const origin="https://ajaxpro.fans";
const image=`${origin}/assets/motm-share.jpg`;
export const publicMatchPath=(slug:string)=>`/stem/${encodeURIComponent(slug)}`;
export const internalVotePath=(slug:string)=>`/club/stemmen/${encodeURIComponent(slug)}`;
export const publicMatchUrl=(slug:string)=>`${origin}${publicMatchPath(slug)}`;
const statusLabel=(status:PublicMatch["status"])=>status==="open"?"Open":status==="closed"?"Gesloten":"Niet beschikbaar";
export const shareMetadata=(match:PublicMatch)=>{
  const unavailable=match.status==="draft";
  const title=unavailable?"AjaxPro Man of the Match":match.status==="closed"?"Bekijk de AjaxPro Man of the Match":"Stem op de AjaxPro Man of the Match";
  const description=unavailable?"Deze stemming is nog niet beschikbaar.":match.status==="closed"?`Bekijk de uitslag van Ajax tegen ${match.opponent}.`:`Ajax tegen ${match.opponent}. Wie was volgens jou de beste Ajacied?`;
  return {title,description,url:publicMatchUrl(match.slug),image};
};
const metaTags=(match:PublicMatch)=>{const meta=shareMetadata(match);return `<title>${esc(meta.title)}</title><meta name="description" content="${esc(meta.description)}"><link rel="canonical" href="${esc(meta.url)}"><meta property="og:type" content="website"><meta property="og:locale" content="nl_NL"><meta property="og:site_name" content="AjaxPro"><meta property="og:title" content="${esc(meta.title)}"><meta property="og:description" content="${esc(meta.description)}"><meta property="og:url" content="${esc(meta.url)}"><meta property="og:image" content="${esc(meta.image)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(meta.title)}"><meta name="twitter:description" content="${esc(meta.description)}"><meta name="twitter:image" content="${esc(meta.image)}">`};
export const renderPublicShare=(match:PublicMatch)=>{const draft=match.status==="draft";const login=`/api/auth/discord-login?returnTo=${encodeURIComponent(internalVotePath(match.slug))}`;return `<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><meta name="theme-color" content="#08090d">${metaTags(match)}<link rel="icon" href="/Favicon/favicon.ico"><link rel="stylesheet" href="/motm.css?v=6"></head><body class="share-page"><header class="share-header"><a href="${origin}"><img src="/assets/ajaxpro-logo.png" alt="AjaxPro"></a></header><main class="share-main"><section class="share-card"><span class="status status-${draft?"draft":match.status}">${statusLabel(match.status)}</span><p class="eyebrow">Man of the Match</p>${draft?`<h1>Deze stemming is nog niet beschikbaar</h1><p>Kom later terug wanneer de stemming is geopend.</p>`:`<h1>${esc(matchTitle(match))}</h1><p>${esc(match.competition)} · ${esc(formatKickoff(match.kickoff_at))}</p><p>${match.status==="closed"?"De stemming is gesloten. Log in om de uitslag te bekijken.":"Wie was volgens jou de beste Ajacied? Log in met Discord om je stem uit te brengen."}</p><a class="button" href="${login}">${match.status==="closed"?"Inloggen en uitslag bekijken":"Inloggen met Discord en stemmen"}</a>`}</section></main></body></html>`};
export const renderPublicNotFound=()=>`<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><title>Stemming niet gevonden | AjaxPro</title><link rel="stylesheet" href="/motm.css?v=6"></head><body class="share-page"><header class="share-header"><a href="${origin}"><img src="/assets/ajaxpro-logo.png" alt="AjaxPro"></a></header><main class="share-main"><section class="share-card"><p class="eyebrow">Man of the Match</p><h1>Stemming niet gevonden</h1><p>Controleer de gedeelde link.</p><a class="button secondary" href="${origin}">Naar AjaxPro</a></section></main></body></html>`;
