import { redirect } from "../../lib/discord-auth";
import { permissions } from "../../lib/permissions.config";
import { getSessionWithPermission } from "../../lib/server-permissions";
import { db } from "../../lib/motm-db";
import { buildSeasonStandings, seasonKeyFor, type SeasonMatch, validSeasonKey } from "../../lib/motm-season";
import { esc, errorPage, formatKickoff, matchTitle, page, pageHeader } from "../../lib/motm-view";
import { synchronizeAllMatches } from "../../lib/motm-scheduling";

const playerRow=(row:any)=>({player_id:String(row.player_id),name_snapshot:String(row.name_snapshot),image_url_snapshot:String(row.image_url_snapshot),votes:Number(row.votes)});
const podiumCard=(row:any)=>`<article class="standing-podium__card standing-podium__card--${row.position}"><div class="standing-rank"><span class="standing-position">${row.position}</span><small>${row.position===1?"Koploper":`${row.position}e plaats`}</small></div><img src="${esc(row.image_url_snapshot)}" alt=""><div class="standing-podium__copy"><strong>${esc(row.name_snapshot)}</strong><span>${row.points} punten</span><small>${row.firsts} ${row.firsts===1?"MOTM-overwinning":"MOTM-overwinningen"}</small></div></article>`;

export async function GET(request:Request){
  const session=await getSessionWithPermission(request,permissions.portalAccess);if(!session)return redirect("/api/auth/discord-login?returnTo=/club/stand");
  const requested=new URL(request.url).searchParams.get("season"),season=requested??seasonKeyFor(new Date());if(!validSeasonKey(season))return errorPage("Ongeldig seizoen","Kies een geldig seizoen, bijvoorbeeld 2026-27.",400,session,"/club/stand","stand");
  try{
    await synchronizeAllMatches();
    const seasonRows=await db()`SELECT DISTINCT season_key FROM motm_matches WHERE deleted_at IS NULL ORDER BY season_key DESC`;
    const rows=await db()`SELECT m.id,m.slug,m.opponent,m.competition,m.kickoff_at,m.home_or_away,m.counts_for_season,p.player_id,p.name_snapshot,p.image_url_snapshot,count(v.player_id)::int votes FROM motm_matches m LEFT JOIN motm_match_players p ON p.match_id=m.id LEFT JOIN motm_votes v ON v.match_id=p.match_id AND v.player_id=p.player_id WHERE m.season_key=${season} AND m.status='closed' AND m.deleted_at IS NULL GROUP BY m.id,p.player_id,p.name_snapshot,p.image_url_snapshot ORDER BY m.kickoff_at DESC,p.name_snapshot`;
    const grouped=new Map<string,SeasonMatch>();for(const row of rows){let match=grouped.get(row.id);if(!match){match={id:row.id,slug:row.slug,opponent:row.opponent,competition:row.competition,kickoff_at:row.kickoff_at,home_or_away:row.home_or_away,counts_for_season:Boolean(row.counts_for_season),players:[]};grouped.set(row.id,match)}if(row.player_id)match.players.push(playerRow(row))}
    const matches=[...grouped.values()],{standings,rounds}=buildSeasonStandings(matches),included=matches.filter(m=>m.counts_for_season);
    const seasons=[...new Set([season,...seasonRows.map((row:any)=>String(row.season_key))])];
    const selector=seasons.length>1?`<details class="season-picker"><summary><span>Seizoen</span><strong>${esc(season)}</strong></summary><div>${seasons.map(key=>`<a href="/club/stand?season=${esc(key)}"${key===season?' class="active" aria-current="page"':""}>${esc(key)}${key===season?" ✓":""}</a>`).join("")}</div></details>`:`<div class="season-current"><span>Seizoen</span><strong>${esc(season)}</strong></div>`;
    const stats=`<div class="season-summary" aria-label="Seizoenssamenvatting"><span><strong>${included.length}</strong> ${included.length===1?"wedstrijd":"wedstrijden"} meegeteld</span><span><strong>${standings.length}</strong> spelers met punten</span></div>`;
    const empty=`<section class="empty"><h2>Nog geen stand</h2><p>Er is nog geen seizoenstand. Na de eerste gesloten MOTM-stemming verschijnt de ranglijst hier.</p></section>`;
    const podium=standings.length?`<section class="standing-leaders"><div class="section-heading"><div><p class="eyebrow">Ajacied van het Jaar</p><h2>Koplopers seizoen ${esc(season)}</h2></div></div><div class="standing-podium" aria-label="Top drie van het seizoen">${standings.slice(0,3).map(podiumCard).join("")}</div></section>`:"";
    const table=standings.length?`<section class="standing-section"><div class="section-heading"><h2>Volledige seizoenstand</h2></div><div class="standing-table"><div class="standing-table__head"><span>#</span><span>Speler</span><span>Punten</span><span>1 / 2 / 3</span></div>${standings.map(row=>`<div class="standing-table__row"><b>${row.position}</b><span class="standing-player"><img src="${esc(row.image_url_snapshot)}" alt=""><strong>${esc(row.name_snapshot)}</strong></span><strong>${row.points}</strong><span>${row.firsts} / ${row.seconds} / ${row.thirds}</span></div>`).join("")}</div></section>`:"";
    const latest=rounds.find(round=>round.match.counts_for_season&&round.results.length);const lastRound=latest?`<section class="last-round"><p class="eyebrow">Laatste ronde</p><h2>${esc(matchTitle(latest.match))}</h2><div>${latest.results.map(row=>`<span><b>${row.rank}</b> ${esc(row.name_snapshot)} <strong>+${row.rank===1?5:row.rank===2?3:1}</strong></span>`).join("")}</div></section>`:"";
    const fixtures=`<section class="season-matches"><div class="section-heading"><h2>Wedstrijden dit seizoen</h2><span>${matches.length} ${matches.length===1?"wedstrijd":"wedstrijden"}</span></div>${matches.length?`<div class="season-match-list">${rounds.map(({match,results})=>`<article class="season-match"><div class="season-match__fixture"><small>${esc(formatKickoff(match.kickoff_at))} · ${match.home_or_away==="home"?"Thuis":"Uit"}</small><h3>${esc(matchTitle(match))}</h3><p>${esc(match.competition)}</p></div><div class="season-match__result"><p class="eyebrow">Top 3</p>${results.length?`<ol class="season-match__podium">${results.map(r=>`<li${r.rank===1?' class="winner"':""}><b>${r.rank}</b><strong>${esc(r.name_snapshot)}</strong><span>${r.percentage}%</span></li>`).join("")}</ol>`:`<p class="season-match__empty">Geen stemmen uitgebracht</p>`}${match.counts_for_season?`<em>✓ Telt mee voor de seizoenstand</em>`:`<em class="excluded">Telt niet mee voor de seizoenstand</em>`}</div><a class="season-match__link" href="/club/stemmen/${esc(match.slug)}">Volledige uitslag →</a></article>`).join("")}</div>`:`<p class="group-empty">Nog geen gesloten wedstrijden in dit seizoen.</p>`}</section>`;
    const scoringHelp=`<details class="scoring-help"><summary>Hoe werkt de puntentelling?</summary><div><h2>Punten voor Ajacied van het Jaar</h2><p>Na iedere meetellende wedstrijd krijgt de nummer 1 vijf punten, de nummer 2 drie punten en de nummer 3 één punt.</p><p>Bij gelijke stemmen bepaalt de speler met de minste eerdere MOTM-overwinningen de hogere plek. Is ook dat gelijk, dan gebruiken we een vaste alfabetische volgorde. Zo is er altijd één unieke top drie.</p><p>Alle punten worden gedurende het gekozen seizoen bij elkaar opgeteld. Wedstrijden die niet meetellen, veranderen de seizoenstand niet.</p></div></details>`;
    return page("Ajacied van het Jaar",`<main class="motm-main standings-main">${pageHeader("Ajacied van het Jaar","Seizoenstand",undefined,undefined,selector)}<div class="standings-intro">${scoringHelp}${stats}</div>${standings.length?podium+table:empty}${lastRound}${fixtures}</main>`,"",session,"stand");
  }catch(error){console.error("Season standings failed",error);return errorPage("Stand niet beschikbaar","Controleer of migratie 004 is uitgevoerd en probeer opnieuw.",503,session,"/club","stand");}
}
