import type { Session } from "../../lib/discord-auth";
import { loadPlayers, toToolPlayer } from "../../lib/player-registry";
import { esc, page, pageHeader } from "../../lib/motm-view";
import { DEFAULT_SOCIAL_THEME, socialFormats, socialOutputFormats, socialThemes } from "../../lib/socials";
import { loadSocialMatchdayFixtures, type SocialMatchdayFixture } from "../../lib/socials-match-context";
import { QUOTE_MAX_LENGTH, QUOTE_NAME_MAX_LENGTH, QUOTE_PHOTO_MAX_BYTES, QUOTE_PHOTO_TYPES, QUOTE_ROLE_MAX_LENGTH } from "../../lib/socials-quote";
import { statsFields } from "../../lib/socials-stats";
import { playerStatsFields } from "../../lib/socials-player-stats";

const serializedFixtures=(fixtures:readonly SocialMatchdayFixture[])=>esc(JSON.stringify(fixtures));
type SocialPlayer=ReturnType<typeof toToolPlayer>;
const serializedPlayers=(players:readonly SocialPlayer[])=>esc(JSON.stringify(players));
const numberInput=(field:typeof statsFields[number],team:"ajax"|"opponent")=>`<label><span>${team==="ajax"?"Ajax":"Tegenstander"}</span><input type="number" inputmode="${field.kind==="integer"?"numeric":"decimal"}" name="${esc(`${field.id}-${team}`)}" data-stat-id="${esc(field.id)}" data-team="${team}" min="${field.min}" max="${field.max}" step="${field.step}" aria-label="${esc(`${field.label} ${team==="ajax"?"Ajax":"tegenstander"}`)}"></label>`;
const playerStatInput=(field:typeof playerStatsFields[number])=>`<label class="player-stat-field"><span>${esc(field.label)}</span><input type="number" inputmode="numeric" name="player-${esc(field.id)}" data-player-stat-id="${esc(field.id)}" min="${field.min}" max="${field.max}" step="${field.step}" aria-label="${esc(field.label)}"></label>`;
const matchLabel=(fixture:SocialMatchdayFixture)=>{const kickoff=new Date(fixture.kickoff_at),score=fixture.goals_home===null||fixture.goals_away===null?"":` · ${fixture.goals_home}–${fixture.goals_away}`,date=new Intl.DateTimeFormat("nl-NL",{day:"numeric",month:"short",year:"numeric",timeZone:"Europe/Amsterdam"}).format(kickoff);return `${fixture.home_team} — ${fixture.away_team} · ${date}${score}`};

const formatButtons=(fixtures:readonly SocialMatchdayFixture[])=>{
  const initial=fixtures.length?"stats":"quote";
  return socialFormats.map(format=>{
    const blocked=format.matchContext==="required"&&!fixtures.length,active=format.id===initial&&!blocked,disabled=format.availability==="planned"||blocked;
    return `<button class="socials-format${active?" is-active":""}" type="button" data-format-id="${esc(format.id)}" data-match-context="${format.matchContext}" aria-pressed="${active}"${disabled?' disabled aria-disabled="true"':""}><strong>${esc(format.title)}</strong><small>${blocked?"Geen wedstrijdcontext beschikbaar":format.availability==="planned"?"Volgt later":esc(format.description)}</small></button>`;
  }).join("");
};

const outputChoices=()=>socialOutputFormats.map((output,index)=>`<label class="socials-output-choice"><input type="radio" name="social-output" value="${esc(output.id)}" data-width="${output.width}" data-height="${output.height}"${index===0?" checked":""}><span><strong>${output.width} × ${output.height}</strong><small>${output.id==="portrait-4x5"?"4:5":"9:16"} · ${esc(output.label)}</small></span></label>`).join("");
const themeChoices=()=>socialThemes.map(theme=>`<label class="socials-theme-choice"><input type="radio" name="social-theme" value="${theme.id}" data-theme-label="${esc(theme.label)}"${theme.id===DEFAULT_SOCIAL_THEME?" checked":""}><span>${esc(theme.label)}</span></label>`).join("");

const statsWorkspace=(fixtures:readonly SocialMatchdayFixture[],matchStatus:string)=>{
  if(!fixtures.length)return `<section class="socials-unavailable" data-stats-unavailable hidden><p class="eyebrow">Wedstrijd vereist</p><h2>Stats is nu niet beschikbaar</h2><p>${esc(matchStatus)} Zodra wedstrijdcontext beschikbaar is, kun je Stats invullen.</p></section><div data-format-workspace="stats" data-stats-workspace hidden></div>`;
  const matchPicker=fixtures.length>1?`<label class="socials-match-picker"><span>Wedstrijd</span><select data-match-select>${fixtures.map(fixture=>`<option value="${esc(fixture.fixture_key)}">${esc(matchLabel(fixture))}</option>`).join("")}</select></label>`:`<div class="socials-selected-match"><span>Wedstrijd</span><strong>${esc(matchLabel(fixtures[0]))}</strong></div>`;
  const fields=statsFields.map(field=>`<div class="stats-field" data-stat-row="${esc(field.id)}"><span class="stats-field-label">${esc(field.label)}</span><div>${numberInput(field,"ajax")}${numberInput(field,"opponent")}</div></div>`).join("");
  const previewRows=statsFields.map(field=>`<li data-preview-stat="${esc(field.id)}"><strong data-preview-value="${esc(field.id)}-ajax">—</strong><span>${esc(field.label)}</span><strong data-preview-value="${esc(field.id)}-opponent">—</strong></li>`).join("");
  return `<div class="socials-workspace" data-format-workspace="stats" data-stats-workspace><div class="socials-controls"><section class="socials-panel" aria-labelledby="stats-match-title"><p class="eyebrow">Wedstrijd</p><h2 id="stats-match-title">Wedstrijdcontext</h2>${matchPicker}<p class="socials-help">${esc(matchStatus)}</p></section><section class="socials-panel" aria-labelledby="stats-fields-title"><p class="eyebrow">Invoer</p><h2 id="stats-fields-title">Ajax en tegenstander</h2><div class="stats-columns" aria-hidden="true"><strong>Ajax</strong><strong>Tegenstander</strong></div><div class="stats-fields">${fields}</div><button class="button secondary stats-reset" type="button" data-stats-reset>Wis statistieken</button></section></div><aside class="socials-preview-panel" aria-labelledby="stats-preview-title"><div class="socials-preview-heading"><div><p class="eyebrow">Live preview</p><h2 id="stats-preview-title">Stats-wireframe</h2></div><span data-preview-ratio>4:5</span></div><article class="stats-preview" data-stats-preview data-aspect="portrait-4x5" data-theme="${DEFAULT_SOCIAL_THEME}"><header><small>AjaxPro · Stats</small><p data-preview-meta>Wedstrijd laden…</p><p data-preview-theme>Thema: Thuis · home</p></header><div class="stats-preview__score"><div><span>Ajax</span><strong data-preview-team="ajax">Ajax</strong></div><b data-preview-score>–</b><div><span>Tegenstander</span><strong data-preview-team="opponent">—</strong></div></div><ol>${previewRows}</ol><footer><span>Wireframe</span><strong data-preview-dimensions>1080 × 1350</strong></footer></article><button class="button secondary socials-download" type="button" disabled>Download PNG · template volgt</button></aside></div>`;
};

const playerStatsWorkspace=(fixtures:readonly SocialMatchdayFixture[],matchStatus:string,players:readonly SocialPlayer[])=>{
  if(!fixtures.length)return `<section class="socials-unavailable" data-player-stats-unavailable hidden><p class="eyebrow">Wedstrijd vereist</p><h2>Spelerstats is nu niet beschikbaar</h2><p>${esc(matchStatus)} Zodra wedstrijdcontext beschikbaar is, kun je Spelerstats invullen.</p></section><div data-format-workspace="player-stats" data-player-stats-workspace hidden></div>`;
  const matchPicker=fixtures.length>1?`<label class="socials-match-picker"><span>Wedstrijd</span><select data-player-match-select>${fixtures.map(fixture=>`<option value="${esc(fixture.fixture_key)}">${esc(matchLabel(fixture))}</option>`).join("")}</select></label>`:`<div class="socials-selected-match"><span>Wedstrijd</span><strong>${esc(matchLabel(fixtures[0]))}</strong></div>`;
  const fields=playerStatsFields.map(field=>playerStatInput(field)).join("");
  const previewRows=playerStatsFields.map(field=>`<li><span>${esc(field.label)}</span><strong data-player-preview-value="${esc(field.id)}">—</strong></li>`).join("");
  return `<div class="socials-workspace" data-format-workspace="player-stats" data-player-stats-workspace hidden><div class="socials-controls"><section class="socials-panel" aria-labelledby="player-stats-match-title"><p class="eyebrow">Wedstrijd</p><h2 id="player-stats-match-title">Wedstrijdcontext</h2>${matchPicker}<p class="socials-help">${esc(matchStatus)}</p></section><section class="socials-panel" aria-labelledby="player-stats-player-title"><p class="eyebrow">Speler</p><h2 id="player-stats-player-title">Kies een speler</h2><label class="socials-match-picker"><span>Ajax-speler</span><select data-player-select>${players.map(player=>`<option value="${esc(player.id)}">${esc(player.name)}${player.shirtNumber===null?"":` · #${player.shirtNumber}`}</option>`).join("")}</select></label><div class="player-stats-fields">${fields}</div><button class="button secondary player-stats-reset" type="button" data-player-stats-reset>Wis spelerstats</button></section></div><aside class="socials-preview-panel" aria-labelledby="player-stats-preview-title"><div class="socials-preview-heading"><div><p class="eyebrow">Live preview</p><h2 id="player-stats-preview-title">Spelerstats-wireframe</h2></div><span data-player-preview-ratio>4:5</span></div><article class="player-stats-preview" data-player-stats-preview data-aspect="portrait-4x5" data-theme="${DEFAULT_SOCIAL_THEME}"><header><small>AjaxPro · Spelerstats</small><p data-player-preview-meta>Wedstrijd laden…</p><p data-player-preview-theme>Thema: Thuis · home</p></header><div class="player-stats-preview__player"><div class="player-stats-preview__photo"><img data-player-preview-photo src="${esc(players[0].imageUrl)}" alt="Foto van ${esc(players[0].name)}"><span data-player-preview-placeholder hidden>Geen foto</span></div><div><strong data-player-preview-name>${esc(players[0].name)}</strong><span data-player-preview-details>#${players[0].shirtNumber??"–"} · ${esc(players[0].position)}</span></div></div><ol>${previewRows}</ol><footer><span>Wireframe</span><strong data-player-preview-dimensions>1080 × 1350</strong></footer></article><button class="button secondary socials-download" type="button" disabled>Download PNG · template volgt</button></aside></div>`;
};

const quoteWorkspace=(initiallyActive:boolean)=>`<div class="socials-workspace" data-format-workspace="quote" data-quote-workspace${initiallyActive?"":" hidden"}><div class="socials-controls"><section class="socials-panel" aria-labelledby="quote-fields-title"><p class="eyebrow">Invoer</p><h2 id="quote-fields-title">Quotegegevens</h2><div class="quote-fields"><label>Quote<textarea name="quote" data-quote-field="quote" maxlength="${QUOTE_MAX_LENGTH}" rows="6" placeholder="Vul de quote in"></textarea><small><span data-quote-count>0</span> / ${QUOTE_MAX_LENGTH} tekens</small></label><label>Naam<input name="quoteName" data-quote-field="name" maxlength="${QUOTE_NAME_MAX_LENGTH}" placeholder="Bijvoorbeeld Jordi Cruijff"></label><label>Rol / functie <em>optioneel</em><input name="quoteRole" data-quote-field="role" maxlength="${QUOTE_ROLE_MAX_LENGTH}" placeholder="Bijvoorbeeld Technisch directeur Ajax"></label></div><div class="quote-photo-field"><span>Foto <em>optioneel</em></span><input type="file" data-quote-photo accept="${QUOTE_PHOTO_TYPES.join(",")}"><small>JPG, PNG of WebP · maximaal ${QUOTE_PHOTO_MAX_BYTES/1024/1024} MB · blijft op dit apparaat</small><p class="quote-photo-error" data-quote-photo-error role="status" hidden></p><button class="button secondary" type="button" data-quote-photo-remove hidden>Verwijder foto</button></div><button class="button secondary quote-reset" type="button" data-quote-reset>Wis Quote</button></section></div><aside class="socials-preview-panel" aria-labelledby="quote-preview-title"><div class="socials-preview-heading"><div><p class="eyebrow">Live preview</p><h2 id="quote-preview-title">Quote-wireframe</h2></div><span data-quote-preview-ratio>4:5</span></div><article class="quote-preview" data-quote-preview data-aspect="portrait-4x5" data-density="normal" data-theme="${DEFAULT_SOCIAL_THEME}"><div class="quote-preview__photo" data-quote-photo-frame hidden><img src="/assets/ajaxpro-logo.png" data-quote-photo-preview alt="Gekozen foto voor de quote"></div><div class="quote-preview__body"><small>AjaxPro · Quote</small><span class="quote-preview__theme" data-quote-preview-theme>Thema: Thuis · home</span><blockquote data-quote-preview-text>“Vul een quote in”</blockquote><div class="quote-preview__byline"><strong data-quote-preview-name>Naam</strong><span data-quote-preview-role hidden></span></div></div><footer><span>Wireframe</span><strong data-quote-preview-dimensions>1080 × 1350</strong></footer></article><button class="button secondary socials-download" type="button" disabled>Download PNG · template volgt</button></aside></div>`;

export const renderSocials = async (session:Session,fixtureLoader=loadSocialMatchdayFixtures,playerLoader=async()=>{const rows=await loadPlayers();return rows.map(toToolPlayer)}) => {
  let fixtures:SocialMatchdayFixture[]=[],fixturesAvailable=true;
  try{fixtures=await fixtureLoader()}catch(error){fixturesAvailable=false;console.error("Socials match context unavailable",error)}
  const players=await playerLoader();
  const matchStatus=fixturesAvailable?(fixtures.length===1?"Wedstrijd uit de centrale wedstrijddata.":`${fixtures.length} recente en aankomende wedstrijden beschikbaar.`):"De wedstrijddata is tijdelijk niet beschikbaar.";
  const initialQuote=!fixtures.length;
  const body=`<main class="motm-main socials-shell" data-socials-root data-social-theme="${DEFAULT_SOCIAL_THEME}">
    ${pageHeader("Socials","AjaxPro staff","/club/tools","Tools")}
    <p class="page-intro">Vul een vast socialformat in en controleer het resultaat direct in de preview.</p>
    <section class="socials-format-section" aria-labelledby="socials-formats-title">
      <div class="section-heading"><h2 id="socials-formats-title">Kies een format</h2></div>
      <div class="socials-format-grid" role="group" aria-label="Socialformat">${formatButtons(fixtures)}</div>
    </section>
    <div class="socials-settings" aria-label="Gedeelde instellingen">
      <section class="socials-output-panel" aria-labelledby="socials-output-title">
        <h2 id="socials-output-title">Uitvoerformaat</h2>
        <div class="socials-output-choices" role="radiogroup" aria-label="Uitvoerformaat">${outputChoices()}</div>
      </section>
      <section class="socials-theme-panel" aria-labelledby="socials-theme-title">
        <h2 id="socials-theme-title">Kleurthema</h2>
        <div class="socials-theme-choices" role="radiogroup" aria-label="AjaxPro kleurthema">${themeChoices()}</div>
      </section>
    </div>
    ${statsWorkspace(fixtures,matchStatus)}${quoteWorkspace(initialQuote)}${playerStatsWorkspace(fixtures,matchStatus,players)}
    <template data-socials-match-context>${serializedFixtures(fixtures)}</template>
    <template data-socials-players>${serializedPlayers(players)}</template>
  </main>`;
  return page("Socials",body,"",session,"tools",undefined,{stylesheets:["/socials.css"],moduleScripts:["/socials/main.mjs"],imageSources:["blob:"]});
};
